# TODO: Yaml language server
alias: !include_dir "{{ .Home }}/aliae/aliases"
env: !include_dir "{{ .Home }}/aliae/envs"
path: !include_dir "{{ .Home }}/aliae/paths"
script: !include_dir "{{ .Home }}/aliae/scripts"
