# yaml-language-server $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json
- name: "[FINDER] Show file extensions"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllExtensions
    type: bool
    value: "{{ Defaults.Finder.ShowFileExtensions }}"
    state: present
  notify: Finder Restart

- name: "[FINDER] Show hidden files"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: string
    value: "{{ Defaults.Finder.ShowHiddenFiles }}"
    state: present
  notify: Finder Restart

- name: "[FINDER] Show path bar"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: "{{ Defaults.Finder.ShowPathBar }}"
    state: present
  notify: Finder Restart

- name: "[FINDER] Set preferred view style"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "{{ Defaults.Finder.PreferredViewStyle }}"
    state: present
  notify: Finder Restart

- name: "[FINDER] Show status bar"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: "{{ Defaults.Finder.ShowStatusBar }}"
    state: present
  notify: Finder Restart

- name: "[FINDER] Set search scope"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "{{ Defaults.Finder.SearchScope }}"
    state: present
  notify: Finder Restart

- name: "[FINDER] Remove items from trash after 30 days"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXRemoveOldTrashItems
    type: bool
    value: "{{ Defaults.Finder.RemoveOldTrash }}"
    state: present
  notify: Finder Restart

- name: "[FINDER] Change extension warning"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: "{{ Defaults.Finder.ChangeExtensionWarning }}"
    state: present
  notify: Finder Restart

- name: "[FINDER] Titlebar icon"
  community.general.osx_defaults:
    domain: com.apple.universalaccess
    key: showWindowTitlebarIcons
    type: bool
    value: "{{ Defaults.Finder.TitlebarIcon }}"
    state: present
  notify: Finder Restart

- name: "[FINDER] Sidebar icon size"
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSTableViewDefaultSizeMode
    type: int
    value: "{{ Defaults.Finder.SidebarIconSize }}"
    state: present
  notify: Finder Restart
