version: "3"

vars:
  PROJECT_DIR:
    sh: git rev-parse --show-toplevel

dotenv: [.config.env]

env:
  PATH: "{{.ROOT_DIR}}/.venv/bin:$PATH"
  VIRTUAL_ENV: "{{.ROOT_DIR}}/.venv"

includes:
  precommit: .taskfiles/PrecommitTasks.yaml

tasks:
  default:
    silent: true
    cmds:
    - task -l
