# yaml-language-server $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json

# - name: Remove all repositories
#   become: true
#   community.general.apt_repo:
#     repo: all
#     state: absent

- name: Enable main repositories
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: no
  with_items:
  - "deb http://archive.ubuntu.com/ubuntu/ {{ansible_distribution_release}} main"
  - "deb http://archive.ubuntu.com/ubuntu/ {{ansible_distribution_release}}-updates main"
  - "deb http://security.ubuntu.com/ubuntu/ {{ansible_distribution_release}}-security main"

- name: Enable universe repositories
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: no
  with_items:
  - "deb http://archive.ubuntu.com/ubuntu/ {{ansible_distribution_release}} universe"
  - "deb http://archive.ubuntu.com/ubuntu/ {{ansible_distribution_release}}-updates universe"
  - "deb http://security.ubuntu.com/ubuntu/ {{ansible_distribution_release}}-security universe"
