# yaml-language-server: $schema=https://raw.githubusercontent.com/shamubernetes/json-schemas/main/google.yamlfmt.schema.json
formatter:
  type: basic
  indent: 2
  line_ending: lf
  retain_line_breaks: true
  retain_line_breaks_single: true
  scan_folded_as_literal: true
  include_document_start: false
  indentless_arrays: true
  disallow_anchors: false
  max_line_length: 0
  drop_merge_tag: true
  pad_line_comments: 1
