- name: 'kccc'
  value: 'kubectl config current-context'
- name: 'kcdc'
  value: 'kubectl config delete-context'
- name: 'kcgc'
  value: 'kubectl config get-contexts'
- name: 'kcn'
  value: 'kubectl config set-context --current --namespace'
- name: 'kcsc'
  value: 'kubectl config set-context'
- name: 'kcuc'
  value: 'kubectl config use-context'
- name: 'kcdelcl'
  value: 'kubectl config delete-cluster'
- name: 'kcdelu'
  value: 'kubectl config delete-user'
- name: 'kcgcl'
  value: 'kubectl config get-clusters'
- name: 'kcgu'
  value: 'kubectl config get-users'
- name: 'kcrc'
  value: 'kubectl config rename-context'
- name: 'kcscr'
  value: 'kubectl config set-credentials'
- name: 'kcscl'
  value: 'kubectl config set-cluster'
- name: 'kcs'
  value: 'kubectl config set'
- name: 'kcu'
  value: 'kubectl config unset'
- name: 'kcv'
  value: 'kubectl config view'
