# yaml-language-server $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json
- name: Set up local environment
  hosts: local
  roles:
  # - {role: vscode, tags: ['vscode']}
  - role: os
    tags:
    - os
    - personal
    - work
    - workstation
  - role: mise
    tags:
    - mise
    - programs
    - personal
    - work
