name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
    paths:
      - 'cloudflare/**'
      - '.github/workflows/worker-deploy.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'cloudflare/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Cloudflare Worker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cloudflare
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun test

      - name: Deploy to Cloudflare Workers
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'cloudflare'
          packageManager: bun
